# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemovie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingseat',
            name='show_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookingseat',
            name='seat_num',
            field=models.IntegerField(default=0),
        ),
    ]
