# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemovie', '0003_auto_20170801_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='starring',
            name='movie',
        ),
        migrations.AlterField(
            model_name='movie',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Starring',
        ),
    ]
