# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemovie', '0004_auto_20170802_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingseat',
            name='user',
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='email_id',
            field=models.CharField(default='poudyalsraj@gmail.com', max_length=50),
        ),
    ]
