# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managemovie', '0006_auto_20170804_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('discription', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingseat',
            name='movie',
        ),
        migrations.DeleteModel(
            name='LogForm',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='producer',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managemovie.MovieGenre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='BookingSeat',
        ),
    ]
