# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managemovie', '0007_auto_20170807_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='synopsisa',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
